// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiljTZEEuu8vWrT9MaH4SRH8GWFU--A9o',
    appId: '1:978017050610:web:ec1c7077a1c4217562d56b',
    messagingSenderId: '978017050610',
    projectId: 'campes-app1',
    authDomain: 'campes-app1.firebaseapp.com',
    databaseURL: 'https://campes-app1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campes-app1.appspot.com',
    measurementId: 'G-JV5SEH4N01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUUH2OEVK7dTs0E4gdOCo2rlD_2N1vh8s',
    appId: '1:978017050610:android:03e8567d6dd204d462d56b',
    messagingSenderId: '978017050610',
    projectId: 'campes-app1',
    databaseURL: 'https://campes-app1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campes-app1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkP6I36tvFW4uS9mQUxlZGyKZ1Bnrg16M',
    appId: '1:978017050610:ios:eecd3c5690a669a762d56b',
    messagingSenderId: '978017050610',
    projectId: 'campes-app1',
    databaseURL: 'https://campes-app1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campes-app1.appspot.com',
    iosClientId: '978017050610-87615f6f3l178u8jna654ri9irms5si0.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusSubsystem',
  );
}
