// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP73N0K9IyLQ1sw1X3PTeIWbccepoSCCQ',
    appId: '1:219929547423:web:762cdc833265149e2288aa',
    messagingSenderId: '219929547423',
    projectId: 'campus-subsystem',
    authDomain: 'campus-subsystem.firebaseapp.com',
    storageBucket: 'campus-subsystem.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIjmYPd-FrcYocrtx8V3P7YK68sP_JLqo',
    appId: '1:219929547423:android:bd56b6fddb093b522288aa',
    messagingSenderId: '219929547423',
    projectId: 'campus-subsystem',
    storageBucket: 'campus-subsystem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtyEhQu4Dmpd-KjXgRjY8sJCmv1qzdFZo',
    appId: '1:219929547423:ios:d7a4b09682df56ce2288aa',
    messagingSenderId: '219929547423',
    projectId: 'campus-subsystem',
    storageBucket: 'campus-subsystem.appspot.com',
    iosClientId: '219929547423-7l24hv3ihvsve6ha993qgjpn29jvs8cd.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusSubsystem',
  );
}
