// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvR68YkB2IY8-ScCn0ZstqKt8-1iBBm1g',
    appId: '1:940741776584:web:df9110151f44e5aef6c1fd',
    messagingSenderId: '940741776584',
    projectId: 'campus-76c01',
    authDomain: 'campus-76c01.firebaseapp.com',
    storageBucket: 'campus-76c01.appspot.com',
    measurementId: 'G-49JQGCHRTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfGyUW0tE0OT-wpkmvSFk9BgJcdEEu-4Q',
    appId: '1:940741776584:android:74f8991d8387c0fff6c1fd',
    messagingSenderId: '940741776584',
    projectId: 'campus-76c01',
    storageBucket: 'campus-76c01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC7ck_UTRL0K5x4ZJlTtYIeC2zhl-8T_c',
    appId: '1:940741776584:ios:f67ae7a8769c5a2df6c1fd',
    messagingSenderId: '940741776584',
    projectId: 'campus-76c01',
    storageBucket: 'campus-76c01.appspot.com',
    iosClientId: '940741776584-dfrhfn39uk50e2fj28kmu51m5d15mqmm.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusSubsystem',
  );
}
